export const SizeGuideData = [
  {
    id: "1",
    diameterOfRing: "۱۳.۰",
    aroundTheRing: "۴۶ میلی‌متر",
    RingSize: "۴۲",
  },
  {
    id: "2",
    diameterOfRing: "۱۳.۴",
    aroundTheRing: "۴۷ میلی‌متر",
    RingSize: "۴۳",
  },
  {
    id: "3",
    diameterOfRing: "۱۳.۷",
    aroundTheRing: "۴۸ میلی‌متر",
    RingSize: "۴۴",
  },
  {
    id: "4",
    diameterOfRing: "۱۴.۰",
    aroundTheRing: "۴۹ میلی‌متر",
    RingSize: "۴۵",
  },
  {
    id: "5",
    diameterOfRing: "۱۴.۳",
    aroundTheRing: "۵۰ میلی‌متر",
    RingSize: "۴۶",
  },
  {
    id: "6",
    diameterOfRing: "۱۴.۶",
    aroundTheRing: "۵۱ میلی‌متر",
    RingSize: "۴۷",
  },
  {
    id: "7",
    diameterOfRing: "۱۵.۰",
    aroundTheRing: "۵۲ میلی‌متر",
    RingSize: "۴۸",
  },
  {
    id: "8",
    diameterOfRing: "۱۵.۳",
    aroundTheRing: "۵۳ میلی‌متر",
    RingSize: "۴۹",
  },
  {
    id: "9",
    diameterOfRing: "۱۵.۶",
    aroundTheRing: "۵۴ میلی‌متر",
    RingSize: "۵۰",
  },
  {
    id: "10",
    diameterOfRing: "۱۵.۹",
    aroundTheRing: "۵۵ میلی‌متر",
    RingSize: "۵۱",
  },
  {
    id: "11",
    diameterOfRing: "۱۶.۲",
    aroundTheRing: "۵۶ میلی‌متر",
    RingSize: "۵۲",
  },
  {
    id: "12",
    diameterOfRing: "۱۶.۵",
    aroundTheRing: "۵۷ میلی‌متر",
    RingSize: "۵۳",
  },
  {
    id: "13",
    diameterOfRing: "۱۶.۸",
    aroundTheRing: "۵۸ میلی‌متر",
    RingSize: "۵۴",
  },
  {
    id: "14",
    diameterOfRing: "۱۷.۲",
    aroundTheRing: "۵۹ میلی‌متر",
    RingSize: "۵۵",
  },
  {
    id: "15",
    diameterOfRing: "۱۷.۵",
    aroundTheRing: "۶۰ میلی‌متر",
    RingSize: "۵۶",
  },
  {
    id: "16",
    diameterOfRing: "۱۷.۸",
    aroundTheRing: "۶۱ میلی‌متر",
    RingSize: "۵۷",
  },
  {
    id: "17",
    diameterOfRing: "۱۸.۱",
    aroundTheRing: "۶۲ میلی‌متر",
    RingSize: "۵۸",
  },
  {
    id: "18",
    diameterOfRing: "۱۸.۴",
    aroundTheRing: "۶۳ میلی‌متر",
    RingSize: "۵۹",
  },
  {
    id: "19",
    diameterOfRing: "۱۸.۸",
    aroundTheRing: "۶۴ میلی‌متر",
    RingSize: "۶۰",
  },
  {
    id: "20",
    diameterOfRing: "۱۹.۱",
    aroundTheRing: "۶۵ میلی‌متر",
    RingSize: "۶۱",
  },
  {
    id: "21",
    diameterOfRing: "۱۹.۴",
    aroundTheRing: "۶۶ میلی‌متر",
    RingSize: "۶۲",
  },
  {
    id: "22",
    diameterOfRing: "۱۹.۷",
    aroundTheRing: "۶۷ میلی‌متر",
    RingSize: "۶۳",
  },
  {
    id: "23",
    diameterOfRing: "۲۰.۰",
    aroundTheRing: "۶۸ میلی‌متر",
    RingSize: "۶۴",
  },
  {
    id: "24",
    diameterOfRing: "۲۰.۳",
    aroundTheRing: "۶۹ میلی‌متر",
    RingSize: "۶۵",
  },
  {
    id: "25",
    diameterOfRing: "۲۰.۶",
    aroundTheRing: "۷۰ میلی‌متر",
    RingSize: "۶۶",
  },
  {
    id: "26",
    diameterOfRing: "۲۱.۰",
    aroundTheRing: "۷۱ میلی‌متر",
    RingSize: "۶۷",
  },
  {
    id: "27",
    diameterOfRing: "۲۱.۳",
    aroundTheRing: "۷۲ میلی‌متر",
    RingSize: "۶۸",
  },
];
